# Generated by Django 4.0.5 on 2022-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('diretor', models.CharField(max_length=256)),
                ('ano', models.CharField(max_length=30)),
            ],
        ),
    ]
